### ISSUE TITLE
Could you include checking links inside iFrames? (Facebook Comments)

### ISSUE THREAD

**Issue by alexgarciab** [rvalitov/backlink-checker#4]
Right now, the script is only able to detect links inside "plain" HTML, but not inside iFrames. A lot of websites do have the Facebook Comments module inserted in the bottom of their articles. Are you able to improve the bash script to be able to detect links inside Facebook Comments? Meaning, scanning for links inside iFrames.

**Comment by rvalitov** [comment]
The problem is not in iFrame here. The problem is that many websites require JS-capable processing. Currently we do here only a simple direct code analysis. Unfortunately I think there's no more space for improvement in this current project.

P.S. I have another project which is not open source. It uses a full fledged browser-like processing of web pages and supports all kinds of links, including indirect links (that work via redirect, short links or link anonymizers). It also takes a screenshot of web pages and marks the detected backlinks there and makes a fancy report.
